dockergen: docker-gen -watch -notify "nginx -s reload" /app/nginx.tmpl /etc/nginx/conf.d/default.conf
certbot: docker-gen -watch -notify "touch /app/mk.txt" /app/certbot.sh.tmpl /app/certbot.sh 
nginx: nginx
