#!/bin/bash

#https://docs.docker.com/docker-hub/builds/advanced/

year=`date -u +%Y`
tag=$DOCKER_REPO:$DOCKER_TAG
if [ "latest" == "$DOCKER_TAG" ] ; then
  tag=$DOCKER_REPO:0.$year
fi
docker tag $IMAGE_NAME $tag
docker push $tag
